# Generated by Django 6.0.7 on 2026-08-04 21:13

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('book', '0002_book_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasketBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_order', models.CharField(max_length=50)),
                ('count', models.IntegerField(default=1)),
                ('age', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(14)])),
                ('card', models.CharField(max_length=16, validators=[django.core.validators.MinLengthValidator(16)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Не выполнено', 'Не выполнено'), ('В Обработке', 'В Обработке'), ('Выполнено', 'Выполнено')], max_length=20)),
                ('choice_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.book')),
            ],
        ),
    ]
