# Generated by Django 6.0.7 on 2026-08-04 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horse_tour', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryhorse',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='commenthorse',
            options={'verbose_name': 'Комент', 'verbose_name_plural': 'Комент'},
        ),
        migrations.AlterModelOptions(
            name='horse',
            options={'verbose_name': 'Конь', 'verbose_name_plural': 'Кони'},
        ),
        migrations.AlterModelOptions(
            name='horsetour',
            options={'verbose_name': 'Конный тур', 'verbose_name_plural': 'Конные туры'},
        ),
        migrations.AlterModelOptions(
            name='reservation',
            options={'verbose_name': 'Бронь', 'verbose_name_plural': 'Броня'},
        ),
    ]
